name: Playwright Tests & Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # --------------------------
      # Checkout repository
      # --------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------
      # Setup Node.js
      # --------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # automatically use latest LTS

      # --------------------------
      # Install dependencies
      # --------------------------
      - name: Install dependencies
        run: npm ci

      # --------------------------
      # Run all tests together (merged)
      # --------------------------
      - name: Run all tests (merged)
        run: |
          rm -rf allure-results/all
          mkdir -p allure-results/all
          npm run test:standard
          cp -r allure-results/* allure-results/all/
          rm -rf allure-results/*
          npm run test:performance
          cp -r allure-results/* allure-results/all/
          rm -rf allure-results/*
          npm run test:locked
          cp -r allure-results/* allure-results/all/

      - name: Generate Allure report (merged)
        run: |
          npx allure generate allure-results/all --clean -o allure-report/all

      # --------------------------
      # Run individual projects
      # --------------------------
      - name: Run standard-user tests
        run: |
          rm -rf allure-results/standard
          npm run test:standard
          cp -r allure-results/* allure-results/standard
          npx allure generate allure-results/standard --clean -o allure-report/standard

      - name: Run performance-glitch-user tests
        run: |
          rm -rf allure-results/performance
          npm run test:performance
          cp -r allure-results/* allure-results/performance
          npx allure generate allure-results/performance --clean -o allure-report/performance

      - name: Run locked-out-user tests
        run: |
          rm -rf allure-results/locked
          npm run test:locked
          cp -r allure-results/* allure-results/locked
          npx allure generate allure-results/locked --clean -o allure-report/locked

      # --------------------------
      # Publish all reports to GitHub Pages
      # --------------------------
      - name: Deploy Allure reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
