name: Playwright Tests & Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run all tests sequentially
      - name: Run all Playwright tests
        run: npm run test:all:report

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
